# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd451727775726e848b499e4da11f722b1d57db50d7278e1a755dcde27e1cc651878a2688e3f4d799160703d761f6795987a389bdbbb3a323f38f5d5cae95c29

test:
  secret_key_base: fa41cb08cfd5d1b919310145126781b523178480126bf5032dbf12e668349839597fb69dadd0bcba0dc87b797bf507a517afdd2b5d4380b60c14b1e5807194d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
